accelerator: "cpu"
# accelerator: 'gpu'
devices: "auto"
# devices:
#   - "cuda:0"
#   - "cuda:1"
part_names:
  - "background"
  - "body"
  - "mirror"
  - "plate"
  - "door"
  - "wheel"
  - "headlight"
  - "window"
test_data_dir: "datasets/coco/bus_square"
min_crop_ratio: 0.6
num_patchs_per_side: 1
patch_size: 512
epochs: 200
output_dir: "/output"
checkpoint_dir: "checkpoints/SLiMe/bus"
save_mask: True
